[env]
BROWSERSLIST="> 0.9% and last 2 versions and not dead"


[tools]
node = "latest"
deno = "2.4"
# esbuild = "0.25.8"


[tasks]
build = { depends = ["build:*"] }
lint = { depends = ["lint:*"] }
serve = { depends = ["lume -s"] }

"build:www" = { depends = "lume" }
"build:css" = [
  "esbuild --bundle --outdir=dist src/missing.css src/missing-prism.css",
  "esbuild --minify --outdir=dist --entry-names=[name].min dist/missing.css dist/missing-prism.css",
]
"build:js" = "rm -rf dist/js && mkdir -p dist && cp -r src/js dist/js"

lume = { hide = true, run = "cd www && echo \"import 'lume/cli.ts'\" | deno run --unstable -A -" }


[alias]
esbuild = "npm:esbuild"
